uses github app

diff --git a/.github/workflows/BuildAndPushToAzureContainerRegistry.yml b/.github/workflows/BuildAndPushToAzureContainerRegistry.yml
--- a/.github/workflows/BuildAndPushToAzureContainerRegistry.yml
+++ b/.github/workflows/BuildAndPushToAzureContainerRegistry.yml
@@ -15,6 +15,13 @@ jobs:
           - name: Set up Docker Buildx
             uses: docker/setup-buildx-action@v1
 
+          - name: Get latest GitHub Actions runner version
+            id: get_runner_version
+            run: |
+              RUNNER_VERSION=$(curl -s https://api.github.com/repos/actions/runner/releases/latest | jq -r '.tag_name' | sed 's/^v//')
+              echo "version=$RUNNER_VERSION" >> $GITHUB_OUTPUT
+              echo "Latest GitHub Actions runner version: $RUNNER_VERSION"
+
           - name: Login to Azure Docker Registry
             uses: azure/docker-login@v2
             with:
@@ -26,7 +33,9 @@ jobs:
           - name: Build and push Docker image
             run: |
               docker build . \
-                -t creuwbfcommonsp.azurecr.io/infrastructure/github-runner:${{ github.sha }} \
+                --platform linux/amd64 \
+                --build-arg GITHUB_RUNNER_VERSION=${{ steps.get_runner_version.outputs.version }} \
+                -t creuwbfcommonsp.azurecr.io/infrastructure/github-runner:${{ github.sha }}
               docker push creuwbfcommonsp.azurecr.io/infrastructure/github-runner:${{ github.sha }}
 
           - name: Generate Token
@@ -40,17 +49,26 @@ jobs:
               revoke: true
 
           
-          - name: Update CONTAINER_IMAGE_NAME variable
+          - name: Update GitHub variables
             env:
               INSTALLATION_TOKEN: ${{ steps.create_token.outputs.token }}
               TARGET_REPO_NAME: 'businessfinland/bf-self-hosted-github-runner'
             run: |
+                # Update CONTAINER_IMAGE_NAME variable
                 curl -X PATCH \
                 -H "Authorization: Bearer $INSTALLATION_TOKEN" \
                 -H "Accept: application/vnd.github+json" \
                 "https://api.github.com/repos/$TARGET_REPO_NAME/actions/variables/CONTAINER_IMAGE_NAME" \
                 -d "{\"value\":\"${{ github.sha }}\"}" \
-                || { echo "Failed to update variable"; exit 1; }
+                || { echo "Failed to update CONTAINER_IMAGE_NAME variable"; exit 1; }
+
+                # Update GITHUB_RUNNER_VERSION variable
+                curl -X PATCH \
+                -H "Authorization: Bearer $INSTALLATION_TOKEN" \
+                -H "Accept: application/vnd.github+json" \
+                "https://api.github.com/repos/$TARGET_REPO_NAME/actions/variables/GITHUB_RUNNER_VERSION" \
+                -d "{\"value\":\"${{ steps.get_runner_version.outputs.version }}\"}" \
+                || { echo "Failed to update GITHUB_RUNNER_VERSION variable"; exit 1; }
 
 
 #          - name: Trigger Deployment Workflow
